🚧 Update to SDK 26.1.100
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🙇🏿🇰🇬🧙🏻🧑🏾‍🦳

Full error log:
Error:  asset 2022-7-25--0-36-14--d823729f-bff6-4ee4-bdf7-03556b2c46c9/main.min.js 242 KiB [emitted] (name: main) 1 related asset
runtime modules 891 bytes 4 modules
modules by path ./node_modules/ 225 KiB
modules by path ./node_modules/destroyable/dist/ 38 KiB
modules by path ./node_modules/destroyable/dist/*.js 35.4 KiB 10 modules
modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB
./node_modules/destroyable/dist/errors/CollisionError.js 1.3 KiB [built] [code generated]
./node_modules/destroyable/dist/errors/NotFoundError.js 1.29 KiB [built] [code generated]
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 54.7 KiB [built] [code generated]
./node_modules/jszip/dist/jszip.min.js 93.8 KiB [built] [code generated]
./node_modules/xyzt/dist/esm/xyzt.js 38.7 KiB [built] [code generated]
./src/zip-import.module.ts 3.78 KiB [built] [code generated] [1 error]
./package.json 732 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\zip-support\src\zip-import.module.ts
./src/zip-import.module.ts 56:102-107
[tsl] ERROR in C:\Users\me\work\collboard\zip-support\src\zip-import.module.ts(56,103)
TS2339: Property 'scale' does not exist on type 'BehaviorSubject<Transform>'.

webpack 5.35.1 compiled with 1 error in 6684 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\zip-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\zip-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\zip-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\zip-support\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\zip-support\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\zip-support\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\zip-support\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\zip-support\node_modules\webpack\lib\Watching.js:201:28)